## Numpy
The Numpy library is the core library for scientific computing in Python. It provides a high performance multidimensional array object, and tools for working with these arrays.


In [1]:
# Import Convention
import numpy as np

In [16]:
# Creating Arrays

a= np.array([1,2,3])
print(a)

b= np.array([(1,2,3), (4,5,6), (7.5,8,9)],dtype =int)
print(b)

c= np.array([(1.5,2,3.2), (4.5,5,6.0), (7,8.2,9.2)],dtype =float)
print(c)


[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1.5  2.   3.2]
 [ 4.5  5.   6. ]
 [ 7.   8.2  9.2]]


In [33]:
# Initial Placeholders
print(np.zeros((3,4))) # Create an array of zeros

print(np.ones((3,4))) # Create an array of zeros

print(np.arange(10,25,5)) # Create an array of evenly spaced values 

print(np.linspace(0,2,9))


print(np.full((2,2),9)) # Creates a constant array



[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[10 15 20]
[ 0.    0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ]
[[ 9.  9.]
 [ 9.  9.]]
[[ 1.  0.]
 [ 0.  1.]]


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\numeric.py:301: FutureWarning: in the future, full((2, 2), 9) will return an array of dtype('int32')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


In [40]:
print(np.eye(2))

print(np.random.random((2,2)))
print(np.empty((3,2)))

[[ 1.  0.]
 [ 0.  1.]]
[[ 0.66811555  0.79430812]
 [ 0.61131007  0.01057955]]
[[  3.45845952e-322   0.00000000e+000]
 [  0.00000000e+000   0.00000000e+000]
 [  0.00000000e+000   0.00000000e+000]]


In [46]:
# I/O 
# Saving & Loading On Disk

np.save('D:/my_array',a)

np.savez('D:/my_array.npz',a,b) # Saves 

np.load('my_array.npy')



array([1, 2, 3])

In [54]:
# Saving & Loading On Text Files
np.loadtxt("D:/myfile.txt")


array(1234.0)

In [58]:
np.genfromtxt("D:/myfile.csv",delimiter =',')

array([ 1.,  2.,  3.,  4.])

In [60]:
np.savetxt("D:/myfile.txt",a,delimiter='')

In [65]:
# Data Types
print(np.int64)
print(np.float32)
print(np.complex)
print(np.bool)
print(np.object)
print(np.string_)
print(np.unicode_)

<class 'numpy.int64'>
<class 'numpy.float32'>
<class 'complex'>
<class 'bool'>
<class 'object'>
<class 'numpy.bytes_'>
<class 'numpy.str_'>


In [75]:
# Inspecting Your Array
print(b.shape)
print(len(b))
print(b.ndim)
print(b.size)
print(b.dtype)
print(b.dtype.name)
print(b.astype(int))

(3, 3)
3
2
9
int32
int32
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [76]:
# Asking for Help
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [109]:
# Array Mathematics
a= np.array([1,2,3])
b= np.array([4,5,6])
print(a-b)
print(a+b)
print(np.add(a,b))
print(np.subtract(b,a))
print(np.divide(b,a))
print(a*b)
print(np.multiply(b,a))
print(np.exp(b))
print(np.sqrt(b))
print(np.sin(b))
print(np.cos(b))
print(np.log(b))
print(np.exp(b))





[-3 -3 -3]
[5 7 9]
[5 7 9]
[3 3 3]
[ 4.   2.5  2. ]
[ 4 10 18]
[ 4 10 18]
[  54.59815003  148.4131591   403.42879349]
[ 2.          2.23606798  2.44948974]
[-0.7568025  -0.95892427 -0.2794155 ]
[-0.65364362  0.28366219  0.96017029]
[ 1.38629436  1.60943791  1.79175947]
[  54.59815003  148.4131591   403.42879349]


In [113]:
# Comparsion
print(a==b)
print(a>b)
print(np.array_equal(a,b))

[False False False]
[False False False]
False


In [125]:
# Aggregate Functions
print(a.sum())
print(a.min())
print(a.max(axis=0))
print(a.cumsum(axis=0))
print(a.mean())
print(np.std(a))



6
1
3
[1 3 6]
2.0
0.816496580928


In [140]:
# Copying Arrays
print(a.view())
print(np.copy(a))
a = np.array([4,2,7])
# Sorting Arrays
a.sort()



[2 4 7]
[2 4 7]
[2 4 7]


In [153]:
# Subsetting ,Slicing ,Indexing 
a=  np.array([(4,2,7),(4,5,6)])


In [155]:
a[0,2]

7

In [157]:
# Slicing
a[0:1]

array([[4, 2, 7]])

In [158]:
a[0:2,1]

array([2, 5])

In [162]:
a[:2]

array([[4, 2, 7],
       [4, 5, 6]])

In [165]:
# Bolean Indexing 
print(a[a>2])

[4 7 4 5 6]


In [166]:
# Array Manipulation
np.transpose(a)

array([[4, 4],
       [2, 5],
       [7, 6]])

In [170]:
a.reshape(3,2)

array([[4, 2],
       [7, 4],
       [5, 6]])